mkdir docs
mkdir ref
mkdir prj
mkdir prj/ae
mkdir prj/pr
mkdir src
mkdir src/img
mkdir src/img/logo
mkdir src/img/illust
mkdir src/img/photo
mkdir src/sound
mkdir src/sound/bgm
mkdir src/sound/se
mkdir src/sound/voice
mkdir src/mov
mkdir src/guide
mkdir src-ph
mkdir work
mkdir work/img
mkdir work/img/logo
mkdir work/img/illust
mkdir work/img/photo
mkdir work/sound
mkdir work/sound/bgm
mkdir work/sound/se
mkdir work/sound/voice
mkdir work/guide
mkdir mov
mkdir audio-master
mkdir out-mediate
mkdir out-master
mkdir final